services:

  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite:3.34.0"
    hostname: azurite
    volumes:
      - "./data/azurite/data/:/data/"
      - "./data/azurite/workspace/:/workspace/"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  service-bus:
    image: "mcr.microsoft.com/azure-messaging/servicebus-emulator:1.1.2"
    hostname: service-bus
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y
    volumes:
      - "./config/service-bus/Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    networks:
      - local-backend
    depends_on:
      - sqledge

  sqledge:
    image: "mcr.microsoft.com/azure-sql-edge:2.0.0"
    hostname: sqledge
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - "./data/sqledge/:/var/opt/mssql/"
    ports:
      - "1433:1433"
    networks:
      - local-backend

networks:
  local-backend:
    driver: bridge
